# Exploratory Data Analysis Course Project
# 12-Apr-2015
# Author: LLN

# plot3.R
# Script to generate Sub Metering line-graphs
# Data frame "data" generated by "load_data.R" script is the source of data for the graph

with(data, plot(dt, Sub_metering_1, type = "l", col = "grey", xlab="", ylab="Energy sub metering"))
with(data, lines(dt, Sub_metering_2, type = "l", col = "blue"))
with(data, lines(dt, Sub_metering_3, type = "l", col = "red"))
legend("topright", pch = 3, col = c("grey", "blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))

# Copy histogram to png graphics device
dev.copy(png, file = "plot3.png", width=480, height=480, units="px")
dev.off()

# End of script