# Exploratory Data Analysis Course Project
# 12-Apr-2015
# Author: LLN

# plot4.R
# Script to generate set of four line-graphs
# Data frame "data" generated by "load_data.R" script is the source of data for the graph

par(mfrow = c(2, 2))
with(data, {
 plot(dt, Global_active_power, type="l", ylab = "Global Active Power", xlab="")
 plot(dt, Voltage, type="l", ylab = "Voltage", xlab="datetime")
 plot(dt, Sub_metering_1, type = "l", col = "grey", xlab="", ylab="Energy sub metering")
 lines(dt, Sub_metering_2, type = "l", col = "blue")
 lines(dt, Sub_metering_3, type = "l", col = "red")
 legend("topright", pch = 3, col = c("grey", "blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
 plot(dt, Global_reactive_power, type="l", ylab = "Global_reactive_power", xlab="datetime")
})

# Copy histogram to png graphics device
dev.copy(png, file = "plot4.png", width=480, height=480, units="px")
dev.off()

# End of script