# Exploratory Data Analysis Course Project
# 12-Apr-2015
# Author: LLN

# plot2.R
# Script to generate Global Active Power line-graph
# Data frame "data" generated by "load_data.R" script is the source of data for the graph

# Generate line graph from data$Global_active_power column (y) and data$dt column(x)
# Set x-axis and y-axis labels appropriately
plot(data$dt, data$Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)")

# Copy histogram to png graphics device
dev.copy(png, file = "plot2.png", width=480, height=480, units="px")
dev.off()

# End of script